### ISSUE TITLE
InaSAFE User Map - Users

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/django-user-map#1]
# Problem 1

In the current implementation of the user map http://users.inasafe.org/ it is possible for users to plot themselves in a different world to most users (ie User Wency) who is a whole world west of everyone else.
# Proposed solution 1

make all the users plot in the same world
# Problem 2

In the current implementation of the user map http://users.inasafe.org/ it is only possible for a user to be  a user, trainer or developer. Do we need to allow individuals to identify as more than one type without making multiple entries to the user map?
# Proposed solution 2

allow users to have many roles
# cc

@akbargumbira @iyan31 @timlinux

**Comment by akbargumbira** [comment]
Hi @Charlotte-Morgan, I have fixed Problem 1 since long time ago but it's not deployed yet..

Problem 2, yes we could..

**Comment by akbargumbira** [comment]
@Charlotte-Morgan: sorry it's not finished for problem 2 :) So you want to allow user to have multiple roles? I wonder what should we do with the consequences like the icon for example..

**Comment by akbargumbira** [comment]
@timlinux @Charlotte-Morgan can we close this?

**Comment by Charlotte-Morgan** [comment]
I think we need users to have multiple roles

**Comment by akbargumbira** [comment]
so we don't need to differentiate their icons, no clusterer for each role, no legend based on the role, and no overlays layer control (on the top right of the screen) for each role?

**Comment by timlinux** [comment]
For cluster markers we can use https://github.com/SINTEF-9012/PruneCluster to indicate roles

And for individual markers we can make hybrid markers (with e.g. pie chart looking icon where each slice represents a role the user belongs to).

**Comment by Charlotte-Morgan** [comment]
Hi @akbargumbira - the new interface (which looks really snappy) does not support users with multiple roles. Please deliver a product to meet user requirements or explain why this is not possible.

**Comment by akbargumbira** [comment]
Hi @Charlotte-Morgan, see https://github.com/AIFDR/inasafe-user-map/issues/50 for the explanation of the drawbacks using multiple roles. If you are OK with that, the multiple roles function is ready on multiple_roles_prune_cluster branch.

**Comment by Charlotte-Morgan** [comment]
hi @iyan31  - i'm looking at @AkbarGumbira user map and wondering how this relates to the database of trainers that HOT is compiling. What format is the trainer database in and can the data be uploaded to the usermap. I'm also thinking that the trainer database will have different attributes to those set up by @AkbarGumbira for the new user map.

please also look at #2 as i'm assuming this will also require a lot of input from HOT regarding events?

**Comment by iyan31** [comment]
Hi @Charlotte-Morgan  - I think it is possible to link it with some kind of web service, although initially it is done through bulk import (csv perhaps). I think we need a small meeting to discuss this, how about after the Rasor meeting on Wednesday?

**Comment by Charlotte-Morgan** [comment]
hi @iyan31 - happy to discuss. Can we wait till @wonderchook & @timlinux are here?

**Comment by timlinux** [comment]
Closing this out - @akber is going to write up new tickets based on changed user requirements following our meeting at HOT.
