### ISSUE TITLE
We should use PruneCluster to make rich clusterings

### ISSUE THREAD

**Issue by timlinux** [inasafe/django-user-map#50]
By using https://github.com/SINTEF-9012/PruneCluster we can let the clusters indicate what roles are repsented in the cluster.

**Comment by timlinux** [comment]
See asl #49 - we should support multiple roles per user

**Comment by akbargumbira** [comment]
Hi @timlinux, for the icon of the marker itself, we don't differentiate based on the role(s)?

**Comment by akbargumbira** [comment]
Hi @timlinux and @Charlotte-Morgan, here is the screenie implementing multiple roles (with PruneCluster):
![1](https://cloud.githubusercontent.com/assets/992519/4970713/afc57de0-6888-11e4-8d8e-291e810c2ac6.png)

There are some drawbacks using multiple roles in the above implementation:
- In my branch now for multiple roles implementation, I don't differentiate the icon for each role. I am not quite sure about this as one user could have 1 or 2 or 3 roles. If we want to differentiate the icon, we need to have: 3C1 (icon for 1 role) + 3C2 (icon for 2 roles) + 3C3 (icon for 3 roles) = 7 icons. Then also we don't need Legend like we had.
-  We can't have overlays layer control (control in the top right) to take a look all the users of a particular role. See here the previous implementation:
  ![2](https://cloud.githubusercontent.com/assets/992519/4970716/baf8c730-6888-11e4-95ab-7465de9f597a.png)
  Basically, overlays control needs different layer for each role to work. In the previous implementation, we have 3 layers for each role (user layer, trainer layer, and developer layer). 
  With the support of multiple roles, I am not certain we can have this nicely. Surely we can still differentiate users to 3 layers, but then if the user has more than one role, there will be multiple markers on the map.
- In the previous implementation, I make the clusterer to only cluster a user to the same role (so, developer will always be clustered with other developer), which is nice IMO.
- IIRC, @timlinux wants to use PruneCluster so we can have something like this http://sintef-9012.github.io/PruneCluster/examples/realworld.50000-categories.html (We can see the comparison among categories for each cluster). But after reading the PruneCluster API, I think we can only assign one category for each marker.

That's the drawbacks. If you all think having multiple roles is above them all, I'll merge the branch (still cleaning it actually now)

**Comment by timlinux** [comment]
Hi @akbargumbira 

In the prune cluster example what is the legend for the colours around each cluster?

![selection_001](https://cloud.githubusercontent.com/assets/178003/4971803/997901a0-68b1-11e4-9129-e4a5f5c6c815.png)

I was thinking that we could differentiate between the roles by using those outer colours / pie slices?

**Comment by akbargumbira** [comment]
@timlinux That represents the percentage of each categories in that cluster. Let's say there are 10 markers, 5 of them have category 1 (red), 3 of them category 2 (green), 2 of them category 3 (blue). Then the cluster is circled 180\* with red, 108\* with green, 72\* with blue

**Comment by Charlotte-Morgan** [comment]
+1 for prune clusters

**Comment by Charlotte-Morgan** [comment]
sounds like we would use multiple entries for a single user with multiple roles and they would then default to be a singular prune that never resolves into separate roles?

**Comment by timlinux** [comment]
@Charlotte-Morgan request to please go ahead with multiple roles

**Comment by akbargumbira** [comment]
ok then, we should get the multiple-role branch up for @Charlotte-Morgan to test what has been done and what's not..
