### ISSUE TITLE
Email all HOT training participants to register on user map

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/django-user-map#59]
HOT has a database of them all. After we deploy the new user map, HOT will email them to register on the map

**Comment by akbargumbira** [comment]
Hi @timlinux @Charlotte-Morgan @adissadis, I have also made django management script to send the email to OSM trainers. If it's ready, this is just a matter of pushing the button. I am waiting your command..

**Comment by Charlotte-Morgan** [comment]
Hi @akbargumbira 
I'm happy with the user map interface if you have made the changes we discussed.
How about a few HOT people try it just to check before you send out to everyone?
@iyan31, @adissadis

**Comment by akbargumbira** [comment]
done
